class WMACConstants:
  # Lead detection
  LEAD_WINDOW_SIZE = 6
  LEAD_PROB = 0.45

  # Slowness detection
  SLOWNESS_WINDOW_SIZE = 10
  SLOWNESS_PROB = 0.55
  SLOWNESS_CRUISE_OFFSET = 1.025

  # Model-stop detection
  MODEL_STOP_HORIZON_S = 7.5
  MODEL_STOP_ARM_DELTA_S = 0.55
  MODEL_STOP_RELEASE_DELTA_S = 0.35
  MODEL_STOP_PROB = 0.5
  MODEL_STOP_MIN_VEGO_KPH = 8.0
  MODEL_STOP_MAX_VEGO_KPH = 110.0
  LEAD_ABSENT_FRAMES = 12  # ~0.6s @ DT_MDL
